- name: update the /etc/hosts file with node name
  tags: etchostsupdate
  become: yes
  become_user: root
  lineinfile:
    path: "/etc/hosts"
    regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}"
    line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}"
    state: present
    backup: yes
  register: etchostsupdate
  when: ansible_hostname != item #or ansible_hostname == item
  with_items: "{{ ansible_play_hosts }}"

- name: add mansionsyrup to /etc/hosts
  become: true
  lineinfile:
    path: "/etc/hosts"
    regexp: ".*\tmansionsyrup"
    line: "192.168.0.120\tmansionsyrup"
    state: present
    backup: yes
