---
- import_tasks: etc-hosts.yml
#- import_tasks: microk8s-prepare.yml
#- import_tasks: microk8s-install.yml
#- import_tasks: microk8s-manager.yml
#- import_tasks: microk8s-workers.yml
- import_tasks: microk8s-addons.yml
