homelab:
  children:
    thicket_pis:

thicket_pis:
  hosts:
    thicket[0:3]:

k8s:
  children:
    k8s_managers:
    k8s_workers:

k8s_managers:
  hosts:
    thicket0:

k8s_workers:
  hosts:
    thicket[1:3]:
